name: "Add plant"
description: "Register a new plant watering schedule"
title: "[Add Plant] {{fields.name}}"
labels: ["add-plant"]
body:
  - type: input
    id: name
    attributes:
      label: "Plant name"
      required: true
  - type: input
    id: start_date
    attributes:
      label: "Start date (YYYY-MM-DD)"
      required: true
  - type: input
    id: frequency_days
    attributes:
      label: "Frequency (days)"
      required: true
