name: "Remove plant"
description: "Stop watering a plant and remove it from the schedule"
title: "[Remove Plant] {{fields.name}}"
labels: ["remove-plant"]
body:
  - type: input
    id: name
    attributes:
      label: "Plant name to remove"
      placeholder: "Exact name as listed"
      required: true
