name: "On remove plant issue"
on:
  issues:
    types: [opened]
jobs:
  remove-plant:
    if: contains(github.event.issue.labels.*.name, 'remove-plant')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.x'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Remove plant from data file
        run: |
          python scripts/remove_plant.py \
            --file _data/plants.yml \
            --name "${{ github.event.issue.title | replace('[Remove Plant] ', '') }}"
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/plants.yml
          git commit -m "chore: remove plant ${{ github.event.issue.title }}"
          git push
      - name: Close issue
        uses: peter-evans/close-issue@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "✅ Removed from your watering schedule!"
