name: "On new plant issue"
on:
  issues:
    types: [opened]
jobs:
  add-plant:
    if: contains(github.event.issue.labels.*.name, 'add-plant')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.x'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Inject new plant
        run: |
          python scripts/add_plant.py \
            --file _data/plants.yml \
            --name "${{ github.event.issue.title | replace('[Add Plant] ', '') }}" \
            --start "${{ github.event.issue.body | match('start_date: (\\d{4}-\\d{2}-\\d{2})')[1] }}" \
            --freq "${{ github.event.issue.body | match('frequency_days: ([0-9]+)')[1] }}"
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/plants.yml
          git commit -m "chore: add plant ${{ github.event.issue.title }}"
          git push
      - name: Close issue
        uses: peter-evans/close-issue@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "✅ Added to your watering schedule!"
